config/routes.rb
OmbuduyApi::Application.routes.draw do

  root :to => 'home#index'

  resources :issues do
    collection do
      get :hot
      get :fixed
    end
    member do
      get :replies
      get :pictures
      get :activity
      get 'fix'
      get 'unfix'
    end
  end

  resources :tags do
    collection do
      get :navigation
    end
    member do
      get :issues
      get :unfixed
    end
  end

  post 'twitter/new' => 'twitter#new'
  post 'twitter/reply' => 'twitter#reply'
  post 'twitter/rt' => 'twitter#rt'
end

app/models/entity.rb
class Entity < ActiveRecord::Base
  attr_accessible :name
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :relevance, :address, :latitude, :longitude, :image_url, :text, :user_id, :twitter_user_id, :tweet_id, :fixed_by, :author

  has_and_belongs_to_many :tags
  has_many :replies

  has_one :user

  before_save do
    if self.fixed_by.to_s =~ /^[0-9]+$/
      self.fixed_by = Entity.find(self.fixed_by).name
    end
  end

  def as_json(options)
    json = {}
    json[:tags] = self.tags.map { |t| t.name }
    json[:id] = self.id
    json[:text] = self.text
    json[:author] = self.author
    json[:created_at] = self.created_at
    json[:relevance] = self.relevance
    json[:fixed_by] = self.fixed_by
    json[:image_url] = self.image_url
    json[:latitude] = self.latitude
    json[:longitude] = self.longitude
    json
  end

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :image_url, :tweet_id, :twitter_reply_to_id, :user_id, :twitter_user_id, :issue_id, :text, :author

  belongs_to :issue

  def as_json(options)
    json = {}
    json[:id] = self.id
    json[:text] = self.text
    json[:author] = self.author
    json[:created_at] = self.created_at
    json
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name, :navigation

  has_and_belongs_to_many :issues
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :twitter_user_id, :email, :nickname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  #before_filter :sleep_it

  def sleep_it
    sleep 0.5
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @issues = Issue.order("updated_at DESC").limit(10)
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def new
  end

  def create
    issue = Issue.create(params["issue"])
    respond_to do |format|
      format.html
      format.json { render json: issue }
    end
  end

  def show
    @issue = Issue.find(params["id"])
    respond_to do |format|
      format.html
      format.json { render json: @issue }
    end
  end

  def index
    @issues = Issue.order('created_at DESC').limit(30)
    respond_to do |format|
      format.html
      format.json{
        render json: @issues
      }
    end
  end

  def edit
  end

  def update
    issue = Issue.find(params[:id]).update_attributes(params["issue"])
    respond_to do |format|
      format.html
      format.json { render json: issue }
    end
  end

  def destroy
    #Podemos hacer que esto sea solo con rol admin
    render status: 405
  end

  def hot
    render json: Issue.where('fixed_by IS NULL').order('relevance DESC').limit(30)
  end

  def fixed
    render json: Issue.where('fixed_by IS NOT NULL').order('created_at DESC').limit(30)
  end

  def replies
    render json: Issue.find(params[:id]).replies
  end
  
  def pictures
    pictures = []
    picture = Issue.find(params[:id]).image_url
    unless picture.nil?
      pictures << {image_url: picture}
    end
    render json: pictures
  end

  def activity
    issue = Issue.find(params[:id])
    activity = []
    activity << {
      author: 'banafederico',
      action: 'creo el reporte',
      date: issue.created_at
    }
    render json: activity
  end

  def fix
    # TODO clean variables, control save action
    issue = Issue.find(params["id"])
    issue.fixed += 1
    issue.save
    redirect_to issue
  end

  def unfix
    issue = Issue.find(params["id"])
    issue.fixed -= 1
    issue.save
    redirect_to issue
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    render :json => Tag.find(params[:id])
  end

  def index
    render :json => Tag.all
  end

  def issues
    render :json => Tag.find(params[:id]).issues.order('created_at DESC')
  end

  def unfixed
    render :json => Tag.find(params[:id]).issues.where('fixed_by IS NULL').order('relevance DESC')
  end

  def navigation
    render :json => Tag.where(:navigation => 1)
  end

end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController

  def new
    if (user = User.where(twitter_user_id: params["user_id"]).first).nil?
      user = User.create(twitter_user_id: params["user_id"].to_i)
    end
    issue = Issue.new(
                      text: params["text"],
                      image_url: params["image_url"],
                      latitude: params["latitude"].to_f,
                      longitude: params["longitude"].to_f,
                      tweet_id: params["tweet_id"],
                      user_id: user.id,
                      author: params["author"]
                      )

    get_tags(params, issue)

    if issue.save
      render json: "/#/reportes/#{issue.id}", status: 201
    else
      render text: "Error", status: 400
    end
  end

  def reply
    unless (issue = give_relevance(params['reply_to_id'])).nil?
      reply = Reply.new(
                        issue_id: issue.id,
                        text: params["message"],
                        tweet_id: params["tweet_id"],
                        user_id: params["user_id"],
                        image_url: params["image_url"],
                        author: params["author"]
                        )

      if reply.save
        render text: "OK", status: 201
      else
        render text: reply.errors, status: 400
      end
    else
      render text: "Error", status: 400
    end
  end

  def rt
    unless (issue = give_relevance(params['tweet_id'])).nil?
      if issue.save
        render text: "OK", status: 201
      else
        render text: issue.errors, status: 400
      end
    else
      render text: "Error", status: 400
    end
  end

  private

  def give_relevance(tweet_id)
    unless (issue = Issue.where(tweet_id: tweet_id).first).nil?
      issue.relevance ||= 0
      issue.relevance += 1
      issue
    end
  end

  def get_tags(params, issue)
    unless params["hashtags"].nil?
      params["hashtags"].each do |hashtag|
        tag = Tag.where(name: hashtag[1]["text"].downcase).first_or_create
        issue.tags << tag
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/home/index.html.erb
<h1>Ombud</h1>
<%= image_tag("logo.png", class: "pull-right") %>
<p>Ombud es un sistema que actúa como <em>Ombudsman</em> entre tú y los entes estatales encargados de cuidar tu ciudad. Te ayuda a informarlos de problemas como calles en mal estado, basura, alumbrado público dañado o situaciones peligrosas en tu barrio.</p>
<p>La idea es catalogar la información y hacer llegar los reportes de incidentes a las entidades o personas que puedan darle una solución. Los datos generados son abiertos y usamos la tecnología de datos abiertos de OpenStreetMap para proveer geolocalizaci&oacute;n a la informaci&oacute;n.
</p>
<%= render_cell :issues, :recent %>

app/views/issues/_map.erb
<script src="http://www.openlayers.org/api/OpenLayers.js"></script>
<% if @issue.latitude != 0  && @issue.longitude != 0 %>
  <div id="mapdiv" style="height:500px; width: 500px;"></div>
  <script>
    map = new OpenLayers.Map("mapdiv");
    map.addLayer(new OpenLayers.Layer.OSM());
    //-34.878842,-56.076877
    var lonLat = new OpenLayers.LonLat( <%= @issue.longitude %>, <%= @issue.latitude %> )
          .transform(
            new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
            map.getProjectionObject() // to Spherical Mercator Projection
          );

    var zoom=16;

    var markers = new OpenLayers.Layer.Markers( "Markers" );
    map.addLayer(markers);

    markers.addMarker(new OpenLayers.Marker(lonLat));

    map.setCenter (lonLat, zoom);
  </script>
<% end %>

app/views/issues/index.html.erb
<% unless @issues.empty? %>
  <%= paginate @issues %>
  <% @issues.each do |issue| %>
    <li><%= link_to issue.text, issue_path(issue) %></li>
  <% end %>
  <%= paginate @issues %>
<% end %>

app/views/issues/show.html.erb
<div>
  <h1>Reporte #<%= @issue.id %></h1>
  <p><strong>Detalle</strong>:
    <blockquote>
      <%= @issue.text %> |
      <%= render_cell :tweets, :issue_tweet, tweet_id: @issue.tweet_id %>
    </blockquote>
  </p>
  <i class="icon-thumbs-up"></i> Relevancia: <%= @issue.relevance %>
  <%= render "map" %>

  <% unless @issue.image_url.empty? %>
    <h3>Foto</h3>
    <img src="<%= @issue.image_url %>"/>
  <% end %>

  <div class="issue-fix-panel">
     <span class="badge badge-success">
       <%= link_to "+", fix_issue_path(@issue) %>
     </span>
     <span class="badge badge-important">
       <%= link_to "-", unfix_issue_path(@issue) %>
     </span>
    <p>
      <%= "Puntaje arreglado: #{@issue.fixed}" %>
    </p>
  </div>

  <div class="btn-group">
    <button class="btn">Agregar información</button>
    <button class="btn">Responder en Twitter</button>
    <button class="btn">Hacer RT</button>
  </div>

  <% unless @issue.replies.empty? %>
    <h3>Respuestas:</h3>
    <ul>
    <% @issue.replies.each do |reply| %>
      <li><%= reply.text %></li>
    <% end %>
    </ul>
  <% end %>
  <div>
  </div>

</div>

app/views/layouts/_header.html.erb
<!-- START HEADER -->
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="brand" href="/">
        <img src="/assets/header-logo.png"/> OmbudUY
      </a>
      <div class="nav-collapse collapse">
        <!-- START LOGIN FORM -->
        <div class="navbar-text pull-right login-form">
        </div>
        <!-- END LOGIN FORM -->
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
<!-- START HEADER -->

app/views/layouts/_sidebar.html.erb
<%= render_cell :issues, :unsolved %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ombudsman</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => '/layouts/header' %>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span4">
        <div class="well sidebar-nav">
          <%= render :partial => '/layouts/sidebar'%>
        </div><!--/.well -->
      </div><!--/span-->
      <div class="span8">
        <div class="hero-unit">
          <%= yield %>
        </div>
      </div><!--/span-->
    </div><!--/row-->

    <hr>

    <footer>
      <p>&copy; <a href="http://2012.desarrollandoamerica.org/">Desarrollando Am&eacute;rica 2012</a> | <a href="http://twitter.com/ombuduy">Ombud en Twitter</a></p>
    </footer>

    <div><!--/.fluid-container-->
</body>
</html>